version: "3"

services:

    database:
        
        image: postgres:12
        volumes:
            - database_data:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - project_network
        
    backend: 

        build: ./backend
        container_name: flask_app
        restart: always
        ports:
            - "5000:5000"
        command: gunicorn --chdir app --workers 4 --bind 0.0.0.0:5000 -m 007 '${GUNICORN_INSTANCE}'
        depends_on: 
            - database
        links: 
            - database
        environment: 
            - POSTGRES_HOST=database
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - project_network

    nginx:
        build: ./nginx
        container_name: nginx_proxy
        restart: always
        expose: 
            - "80"
        ports:
            - "80:80"
        networks:
            - project_network

volumes:
    database_data:
        driver: local

networks:
    project_network: